### PR TITLE
fixed encoding issue

### PR DESCRIPTION
**Pull request by aminoa**
the best-paper notebook needed an encoding to be specified, else I got (charmap' codec can't encode characters in position 7847-7848: character maps to <undefined>), at least when running on Windows 11; I chose UTF-8 arbitrarily

### CODE REVIEW

**Comment by sachiniyer** [comment]
just curious what python version and version of libraries are you using.

**Comment by sachiniyer** [comment]
also utf-8 might be an interesting choice. Depending on the encoding we can end up with stuff like `UniversitÃ© de MontrÃ©al,` from the html.

I worked around this by creating aliases in `data/universities.csv` however, there may be a better way to do it. (P.S. you can also get the output of this in that `data/best-paper.csv` if you use the download link if you want.

**Comment by aminoa** [comment]
Python 3.11.4, should have the same versions as requirements.txt, UTF-8 was completely arbitrary, there may be a better choice.

**Comment by sachiniyer** [comment]
Okay ran it and did a diff, and this was it. Which I am fine with. Merging. Thanks for the contribution.

```diff
4389c4389
< Laurent Massoulié & Milan Vojnović|Microsoft|SIGMETRICS| Performance|2005|1
---
> Laurent Massoulié & Milan Vojnovi&cacute|Microsoft|SIGMETRICS| Performance|2005|1
```

**Pull request merged**
